<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

/**
 * Cross-engine data export — dumps every user-data table to JSON Lines
 * under storage/app/exports/{timestamp}/. Pairs with data:import.
 *
 * Excludes Laravel framework + auth/session tables (re-created on the target,
 * not portable across deploys). The full exclude list lives in EXCLUDED_TABLES.
 */
class DataExport extends Command
{
    protected $signature = 'data:export
        {--out= : Custom output directory (default: storage/app/exports/YYYYMMDD-HHMMSS)}
        {--chunk=1000 : Rows per chunk when streaming large tables}
        {--include= : Comma-separated table allowlist (overrides default scoping)}';

    protected $description = 'Dump all user-data tables to JSON Lines for cross-environment migration.';

    private const EXCLUDED_TABLES = [
        // Framework infrastructure — regenerated by migrate on the target
        'migrations',
        // Session/cache/queue — environment-specific, not portable
        'sessions', 'cache', 'cache_locks',
        'jobs', 'failed_jobs', 'job_batches',
        // Auth artifacts — should be re-issued on the new env
        'password_reset_tokens', 'personal_access_tokens', 'api_tokens',
        // Debug
        'telescope_entries', 'telescope_entries_tags', 'telescope_monitoring',
    ];

    public function handle(): int
    {
        $chunk = (int) $this->option('chunk');
        $outBase = $this->option('out') ?: storage_path('app/exports/' . date('Ymd-His'));

        if (!is_dir($outBase) && !mkdir($outBase, 0755, true) && !is_dir($outBase)) {
            $this->error("Cannot create output directory: {$outBase}");
            return self::FAILURE;
        }

        $allTables = $this->listTables();
        $include = $this->option('include');
        if ($include) {
            $requested = array_map('trim', explode(',', $include));
            $tables = array_values(array_intersect($requested, $allTables));
            $missing = array_diff($requested, $allTables);
            foreach ($missing as $m) $this->warn("  skipping (not in DB): {$m}");
        } else {
            $tables = array_values(array_diff($allTables, self::EXCLUDED_TABLES));
        }

        if (empty($tables)) {
            $this->error('No tables to export.');
            return self::FAILURE;
        }

        $this->info("Exporting " . count($tables) . " tables to {$outBase}");
        $this->info("Driver: " . DB::getDriverName());

        $manifest = [
            'exported_at' => now()->toIso8601String(),
            'source_driver' => DB::getDriverName(),
            'source_database' => DB::getDatabaseName(),
            'chunk_size' => $chunk,
            'tables' => [],
        ];

        $totalRows = 0;
        foreach ($tables as $table) {
            $count = $this->exportTable($table, $outBase, $chunk);
            $manifest['tables'][$table] = $count;
            $totalRows += $count;
        }

        file_put_contents(
            $outBase . DIRECTORY_SEPARATOR . 'manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );

        $this->info("");
        $this->info("Export complete: {$totalRows} rows across " . count($tables) . " tables");
        $this->info("Output: {$outBase}");
        $this->info("Next: tar/zip this directory and copy to the target host, then run:");
        $this->info("  php artisan data:import --in=/path/to/exports/{$this->basename($outBase)}");

        return self::SUCCESS;
    }

    private function exportTable(string $table, string $outBase, int $chunk): int
    {
        $path = $outBase . DIRECTORY_SEPARATOR . $table . '.jsonl';
        $handle = fopen($path, 'w');
        if (!$handle) {
            $this->error("  {$table}: cannot open {$path} for write");
            return 0;
        }

        $rowCount = 0;
        try {
            // Use orderBy + chunkById when an `id` column exists for memory-safe streaming.
            // Fallback to chunk() with explicit orderBy for tables without `id`.
            $hasId = $this->hasIdColumn($table);
            $query = DB::table($table);

            if ($hasId) {
                $query->orderBy('id')->chunkById($chunk, function ($rows) use ($handle, &$rowCount) {
                    foreach ($rows as $row) {
                        fwrite($handle, json_encode((array) $row, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n");
                        $rowCount++;
                    }
                });
            } else {
                $query->chunk($chunk, function ($rows) use ($handle, &$rowCount) {
                    foreach ($rows as $row) {
                        fwrite($handle, json_encode((array) $row, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n");
                        $rowCount++;
                    }
                });
            }
        } finally {
            fclose($handle);
        }

        if ($rowCount === 0) {
            // Drop the empty file — keeps the export dir tidy.
            @unlink($path);
        }

        $this->line(sprintf('  %-40s %s rows', $table, number_format($rowCount)));
        return $rowCount;
    }

    private function listTables(): array
    {
        return match (DB::getDriverName()) {
            'sqlite' => DB::table('sqlite_master')->where('type', 'table')->where('name', 'not like', 'sqlite_%')->orderBy('name')->pluck('name')->toArray(),
            'mysql' => array_map(fn($r) => array_values((array) $r)[0], DB::select('SHOW TABLES')),
            'pgsql' => DB::table('information_schema.tables')->where('table_schema', 'public')->orderBy('table_name')->pluck('table_name')->toArray(),
            'sqlsrv' => DB::table('information_schema.tables')->where('table_type', 'BASE TABLE')->orderBy('table_name')->pluck('table_name')->toArray(),
            default => throw new \RuntimeException('Unsupported driver: ' . DB::getDriverName()),
        };
    }

    private function hasIdColumn(string $table): bool
    {
        try {
            return in_array('id', \Schema::getColumnListing($table), true);
        } catch (\Throwable) {
            return false;
        }
    }

    private function basename(string $path): string
    {
        return basename(rtrim($path, '/\\'));
    }
}
